# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4pzQStFZ6TfZWkatpXiIQz3PADy8CyV
"""

money = input("How much money do you have? ")
expense = input("Add an expense or income record with description and amount: ")
word,item = expense.split()
print("Now you have %d dollars." % (int(money) + int(item)))