# -*- coding: utf-8 -*-
"""109006239_Darrell Nathaniel Prayogi楊輝_hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y6bc5kacaKC7TOG3W26z5JOy-4UcP7la
"""

import sys
import os
def printRed(text): print("\033[91m {}\033[00m" .format(text)) 
def printGreen(text): print("\033[92m {}\033[00m" .format(text)) 

def initialize():
    filename = "records.txt"
    if os.path.exists(filename):
        try:
            with open(filename) as f:
                files = f.readlines()
                records = []
                balance = 0
                welcome_balance = 0
                flag = 0
                for i in range(0,len(files)):
                    line = files[i]
                    if line == files[0]:
                        balance = int(line.strip())
                    else:
                        desc,amt = line.strip().split()
                        records.append((desc, int(amt)))
                        if flag == 0 :
                            welcome_balance = balance + int(amt)
                            flag = 1
                        else : 
                            welcome_balance = welcome_balance + int(amt)
                print(f"Welcome back! Your balance is {welcome_balance} dollars.\n")
        except:
            printRed("Invalid format in records.txt. Deleting the contents.")
            with open(filename, 'w') as f:
                f.write('')
            records = []
            balance = 0
            try:
              balance = int(input("How much money do you have? "))
            except ValueError:
              balance = str(0)
              printRed("Invalid value for money. Set to 0 by default")
    else:
        records = []
        balance = 0
        try:
          balance = int(input("How much money do you have? "))
        except ValueError:
          balance = str(0)
          printRed("Invalid value for money. Set to 0 by default")
    return balance, records


def add(records):
    print("Add an expense or income record with description and amount:")
    try:
        desc, amt = input().split()
        try:
            amt = int(amt)
            records.append((desc, int(amt)))
            print()
        except ValueError:
            printRed("Invalid value for money. The amount should be a number.")
            printRed("Fail to add a record.\n")
    except ValueError:
        printRed("Invalid input format. The input should be in the format: <description> <amount>")
        printRed("Fail to add a record.\n")
    return records


def view(initial_money, records):
    print("Here's your expense and income records:")
    print("Description          Amount")
    print("==================== ======")
    for desc, amt in records:
        print(f"{desc.ljust(20)} {amt:>5}")
    print("==================== ======")
    total_balance = initial_money
    if records:
      for desc, amt in records:
          total_balance += int(amt)
    else:
      total_balance = initial_money
    printGreen(f"Now you have {total_balance} dollars.")



def delete(records,initial_money):
    try:
        desc, amt = input("Which record do you want to delete? ").split()
        amt = int(amt)
        found = False
        for i in range(len(records)):
            if records[i][0] == desc and records[i][1] == amt:
                if desc.startswith("-"):
                    initial_money += amt
                else:
                    initial_money -= amt
                del records[i]
                found = True
                break
        if not found:
            print(f"There's no record with {desc} {amt}. Fail to delete a record.\n")
    except ValueError:
        printRed("Invalid format. The input should be in the format: <description> <amount>. e.g.: food breakfast -50 \nFail to delete a record.\n")
    return records


def save(initial_money, records):
    with open(filename, "w") as f:
        f.write(f"{balance}\n")
        for desc, amt in records:
            f.write(f"{desc} {amt}\n")
          
    print("Goodbye!")


# Main program
filename = "records.txt"
balance, records= initialize()

while True:
    command = input('\nWhat do you want to do (add / view / delete / exit)? ')
    if command == 'add':
        records = add(records)
    elif command == 'view':
        view(balance, records)
    elif command == 'delete':
        records = delete(records,balance)
    elif command == 'exit':
        save(balance, records)
        break
    else:
        sys.stderr.write('Invalid command. Try again.\n')